name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
        node: [20, 22, 24]
      fail-fast: false

    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@v1

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck
